### ISSUE TITLE
pagination-service.d.ts error TS1005: Build:'=' expected

### ISSUE THREAD

**Issue by ialex90** [michaelbromley/ng2-pagination#81]
Hi there,

I am having troubles with the typings of the library, I've been looking for the typings in the typing source but they are not there, they are in the dist folder.

So, if I am running the project by node, there is not problem, but when I am running up with Visual Studio. I get 2 errors:

> .....\UI\node_modules\ng2-pagination\dist\pagination-service.d.ts(30,14): error TS1005: Build:'=' expected.
> 
> ......\UI\node_modules\ng2-pagination\dist\pagination-service.d.ts(30,23): error TS1005: Build:';' expected.

I tried to include the typings on the bootstrap file unsuccessfully. Any idea? Thanks!

**Comment by michaelbromley** [comment]
Hi,

What version of Angular and this library are you using?

**Comment by LasseBrun** [comment]
Hi,

I have the same problem, and same error messages. 

I use Angular 2.0.1 and ng2-pagination 0.5.1.

**Comment by ialex90** [comment]
Sorry, couldn't reply before, same versions from here. I fixed downgrading the version of ng2-pagination.

**Comment by LasseBrun** [comment]
Thanks @ialex90.  That worked for me too.

**Comment by Sk421** [comment]
Hi,
I have same issue.
Can you please tell me Downgrade to which version?

**Comment by LasseBrun** [comment]
Hi,

Version 0.4.1 worked for me.

**Comment by Sk421** [comment]
Thanks LasseBrun for your reply.

but still not working,

my app.module.ts file

import { NgModule }       from '@angular/core';
import { BrowserModule }  from '@angular/platform-browser';
import { AppComponent }   from './app.component';
import { PaginatePipe, PaginationService, PaginationControlsCmp } from 'ng2-pagination';
@NgModule({
  
  imports: [
    BrowserModule, PaginatePipe],
  
  declarations: [
    AppComponent, PaginationControlsCmp
  ],
  providers:[PaginationService],
  
  bootstrap: [ AppComponent ]
})
export class AppModule {
}

it is hitting http://localhost:3000/ng2-pagination

instead of  http://localhost:3000

**Comment by Sk421** [comment]
Thanks LasseBurn.

Now the problem is I am getting ' http://localhost:3000/ng2-pagination 404 (Not Found)' error.

**Comment by ialex90** [comment]
@Sk421 You are importing the components instead the module, that's wrong.
https://github.com/michaelbromley/ng2-pagination/issues/79#issuecomment-252974392

**Comment by Sk421** [comment]
Thanks for your reply @ialex90 
Now I am doing this "import { Ng2PaginationModule } from 'ng2-pagination';".
But getting error.

**Comment by ialex90** [comment]
@Sk421 please, provide more info about the error, paste it here and the code for the ngmodule too.

**Comment by Sk421** [comment]
App.module.ts file

import { NgModule }       from '@angular/core';
import { BrowserModule }  from '@angular/platform-browser';
import { AppComponent }   from './app.component';
import { Ng2PaginationModule } from 'ng2-pagination';

@NgModule({
  
  imports: [
    BrowserModule, Ng2PaginationModule],
  
  declarations: [
    AppComponent
  ],
  providers:[],
  
  bootstrap: [ AppComponent ]
})
export class AppModule {
}


Error:
zone.js:1274 GET http://localhost:3000/ng2-pagination 404 (Not Found)scheduleTask @ zone.js:1274ZoneDelegate.scheduleTask @ zone.js:216Zone.scheduleMacroTask @ zone.js:153(anonymous function) @ zone.js:1304send @ VM1834:3fetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781ZoneAwarePromise @ zone.js:478(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407ZoneDelegate.invoke @ zone.js:203Zone.run @ zone.js:96(anonymous function) @ zone.js:462ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136drainMicroTaskQueue @ zone.js:368ZoneTask.invoke @ zone.js:308
(index):19 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-pagination(…)(anonymous function) @ (index):19ZoneDelegate.invoke @ zone.js:203Zone.run @ zone.js:96(anonymous function) @ zone.js:462ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136drainMicroTaskQueue @ zone.js:368ZoneTask.invoke @ zone.js:308

**Comment by Sk421** [comment]
I added:
<script src="node_modules/ng2-pagination/dist/ng2-pagination-bundle.js"></script> in index.html. 
Now it is working.

Thanks for your replies @ialex90  and @LasseBrun .

**Comment by Sk421** [comment]
Thanks for your replies @ialex90  and @LasseBrun .

I have solved the problem. I added a script file in index.html.

**Comment by ialex90** [comment]
@Sk421 Happy to help even this wasn't the best place for that. Let's not forget the subject of the problem, 
So, any news about the issue?

**Comment by michaelbromley** [comment]
Hi. Great to see people stepping in to help one another, thanks 👍🏼

Re the original issue, I'll have time later this week to look into it. Is everyone here using systemjs?

**Comment by LasseBrun** [comment]
Hi,

Yes, I'am using systemjs.

**Comment by ialex90** [comment]
@michaelbromley me too, thanks :)

**Comment by ialex90** [comment]
I have the feeling that this problem could be solved with the latest version of Typescript, and that just happen in lower than TS 2.0.x, Can you check if that works for you @LasseBrun ?

**Comment by LasseBrun** [comment]
I use TS 2.0.3. But it might be something wrong with my gulp-typescript. I'll take a closer look at it tomorrow!

**Comment by michaelbromley** [comment]
@ialex90 The line that your original error points to is:

```TypeScript
    readonly defaultId: string;
```

This suggests to me that the error is due to the fact that this lib is now built with TypeScript 2.x, and perhaps your version of TypeScript is older and does not understand the `readonly` keyword, which is new.

Check into that.

**Comment by ialex90** [comment]
@michaelbromley this might be helpful:

https://github.com/ng-bootstrap/ng-bootstrap/issues/904#issuecomment-254542060

:)

**Comment by michaelbromley** [comment]
@ialex90 Thanks, that's good info. So in the next release I will make it compatible with TS 1.8+. 👍
